### ISSUE TITLE
Sciplot submodule?

### ISSUE THREAD

**Issue by r-barnes** [JPenuchot/ctbench#19]
Is it possible to set sciplot up so that it can be pulled from a submodule or similar without requiring a system-wide install?

openjournals/joss-reviews#5165

**Comment by JPenuchot** [comment]
Hi, vcpkg provides a package for Sciplot for local installs that doesn't break compatibility with CMake's `find_package`.

I'll work on it and come back to you as soon as a decent (ie. simple and documented) vcpkg integration is ready.

**Comment by JPenuchot** [comment]
I've added the instructions for Sciplot local install using vcpkg, and this method is now used to build ctbench and the tests in the CI for both Ubuntu and Archlinux. I'm closing the issue, thanks for your feedback.
