### ISSUE TITLE
CMake Error: Could not read presets

### ISSUE THREAD

**Issue by r-barnes** [JPenuchot/ctbench#21]
Trying to use cmake 3.22.1 to run
```
cmake --preset release
```
per the installation instructions returns
```
CMake Error: Could not read presets from /z/ctbench: Unrecognized "version" field
```

https://github.com/openjournals/joss-reviews/issues/5165

**Comment by JPenuchot** [comment]
Hello, I've not been able to reproduce this issue on Ubuntu 23.04. This might be related to the CMake version. Please let me know if you encounter this problem on CMake 3.25.

**Comment by JPenuchot** [comment]
Issue not reproducible on Ubuntu 23.04 otherwise tests would not compile on the CI. Closing the issue, feel free to reopen if I missed something.
