### ISSUE TITLE
Make prereq software more apparent

### ISSUE THREAD

**Issue by r-barnes** [JPenuchot/ctbench#22]
It'd be handy if you made a note in the readme that running
```
sudo apt install nlohmann-json3-dev
```
installs a necessary prerequisite. Perhaps there are others as well?

https://github.com/openjournals/joss-reviews/issues/5165

**Comment by JPenuchot** [comment]
Hi, there are other dependencies. Ubuntu is a bit difficult to deal with as it splits packages in dev and non-dev parts. Once again the Ubuntu CI I'll set up will be useful to find out the minimal set of required packages and add it to the docs.

**Comment by JPenuchot** [comment]
Hello, the Ubuntu 23.04 CI was setup successfully, I've added a minimal list of required Ubuntu packages to the documentation. Feel free to close if this satisfies your expectations or give additional feedback if something is missing.

**Comment by JPenuchot** [comment]
I'm closing the issue as both apt and vcpkg package dependencies are now provided in the doc.
