### ISSUE TITLE
Build failed with Boost 1.86

### ISSUE THREAD

**Issue by Osyotr** [JPenuchot/ctbench#39]
I'm updating Boost in vcpkg (https://github.com/microsoft/vcpkg/pull/40465) and the package `ctbench` fails to build.
Please see the attached log.

[install-x64-linux-dbg-out.log](https://github.com/user-attachments/files/17090907/install-x64-linux-dbg-out.log)

**Comment by BillyONeal** [comment]
Might be fixed by https://github.com/JPenuchot/ctbench/commit/d61e61c6e6693c768f728c58bfbe3f07e404b9f7 ?

**Comment by Osyotr** [comment]
Yeah fixed by d61e61c6e6693c768f728c58bfbe3f07e404b9f7.
